### ISSUE TITLE
I think the new release (2.3 & 2.4) causes incompatiblities with PHP return types

### ISSUE THREAD

**Issue by netzarbeiter** [contao/manager-plugin#16]
I'm using the post-release task from mage to clear the opcache. With the new version of the manager-plugin the task has failed.

```
[2018-07-09 13:25:24] magephp.DEBUG: Running task [Exec] Clearing Opcache (exec) [] []
[2018-07-09 13:25:24] magephp.INFO: ssh -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ssh@domain.com "cd /home/user/public_html/domain.com/releases/20180709132456 && vendor/bin/contao-console cache:accelerator:clear --opcode" [] []
[2018-07-09 13:25:24] magephp.DEBUG:  Fatal error: Uncaught TypeError: Return value of Contao\ManagerPlugin\Bundle\Parser\DelegatingParser::addParser() must be an instance of Contao\ManagerPlugin\Bundle\Parser\void, none returned in /home/user/public_html/domain.com/releases/20180709132456/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php:30 Stack trace: #0 /home/user/public_html/domain.com/releases/20180709132456/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(131): Contao\ManagerPlugin\Bundle\Parser\DelegatingParser->addParser(Object(Contao\ManagerPlugin\Bundle\Parser\JsonParser)) #1 /home/user/public_html/domain.com/releases/20180709132456/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(227): Contao\ManagerBundle\HttpKernel\ContaoKernel->getBundleLoader() #2 /home/user/public_html/domain.com/releases/20180709132456/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(53): Contao\ManagerBundle\HttpKernel\ContaoKernel->addBundlesFromPlugins(Array) #3 /home/user/public_html/domain.com in /home/user/public_html/domain.com/releases/20180709132456/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 30  [] []
[2018-07-09 13:25:24] magephp.ERROR:  [] []
[2018-07-09 13:25:24] magephp.DEBUG: Task [Exec] Clearing Opcache (exec) finished with FAIL [] []

```

Going back to version 2.2 (`"contao/manager-plugin": "2.2.*"`) did the trick for me.

**Comment by leofeyer** [comment]
Here is the error message and stack trace in a more readable format:

```
Fatal error: Uncaught TypeError: Return value of Contao\ManagerPlugin\Bundle\Parser\DelegatingParser::addParser() must be an instance of Contao\ManagerPlugin\Bundle\Parser\void, none returned in vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php:30
#0 vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(131): Contao\ManagerPlugin\Bundle\Parser\DelegatingParser->addParser(Object(Contao\ManagerPlugin\Bundle\Parser\JsonParser))
#1 vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(227): Contao\ManagerBundle\HttpKernel\ContaoKernel->getBundleLoader()
#2 vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(53): Contao\ManagerBundle\HttpKernel\ContaoKernel->addBundlesFromPlugins(Array)
#3 /home/user/public_html/domain.com in vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 30
```

**Comment by leofeyer** [comment]
Since the PHP parses thinks that there is a `Contao\ManagerPlugin\Bundle\Parser\void` class, I figure you do not have PHP 7.1?

**Comment by netzarbeiter** [comment]
PHP Version 7.2.6 is running

**Comment by leofeyer** [comment]
Are you sure? Apparently PHP does not recognize the `void` keyword and thinks it refers to a class.

**Comment by netzarbeiter** [comment]
Sorry, PHP 5.6.

**Comment by leofeyer** [comment]
Ok. Still its weird that Composer gave you version 2.3 of the plugin, as it defines PHP 7.1 as minimum requirement: https://github.com/contao/manager-plugin/blob/2.3/composer.json#L13

**Comment by netzarbeiter** [comment]
After private lessons with Yanick, it works now. I had a mess of PHP versions:

- local PHP 7.2.1 (cli) (built: Jan 15 2018 12:20:50) ( NTS )
- hoster PHP 7.0.30 (cli) (built: Jun 14 2018 05:33:09) ( NTS )
- hoster PHP 5.6.36

Should I close the ticket?

**Comment by leofeyer** [comment]
In this case yes. 😄
